sass:
  style: compressed
  sass_dir: _sass

collections:
  updates:
    output: true
  updatesfr:
    output: true

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", ".idea"]