sass:
  style: compressed
  sass_dir: _sass

baseurl: ""
url: "http://localhost:4000/"

collections:
  updates:
    output: true

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", ".idea"]